# new env: conda env create -f requirements.yaml
# update env: conda env update -f requirements.yaml

name: ulib
channels:
  - conda-forge
dependencies:
  - python=3.11
  - tqdm
  - clearml
  - pillow
  - numpy
  - matplotlib
  - ipywidgets
  - pip
  - ipykernel
  - tensorboard
  - pip:
    - torch
    - torchvision
    - torchaudio
    - mealpy
    - robustbench
    - torchattacks